service: objectionjs-graphql-starter

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules:
    forceInclude:
      - pg
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn

package:
  individually: true

functions:
  graphql:
    handler: ./src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
